insert into giaovien (hoten_gv) values ('Sholom Toffanini');
insert into giaovien (hoten_gv) values ('Salomo O''Dee');
insert into giaovien (hoten_gv) values ('Pepito Dyne');
insert into giaovien (hoten_gv) values ('Jilleen Daveren');
insert into giaovien (hoten_gv) values ('Agata Death');
insert into giaovien (hoten_gv) values ('Claudius Kerner');
insert into giaovien (hoten_gv) values ('Augy Ivanishev');
insert into giaovien (hoten_gv) values ('Alic MacNucator');
insert into giaovien (hoten_gv) values ('Ernesta Perham');
insert into giaovien (hoten_gv) values ('Ferdinand Le feaver');
insert into giaovien (hoten_gv) values ('Grange Wackly');
insert into giaovien (hoten_gv) values ('Thoma Petruska');
insert into giaovien (hoten_gv) values ('Courtnay Padrick');
insert into giaovien (hoten_gv) values ('Ashlen McDaid');
insert into giaovien (hoten_gv) values ('Maynard Burdekin');
insert into giaovien (hoten_gv) values ('Trudy Flowitt');
insert into giaovien (hoten_gv) values ('Korie Dominguez');
insert into giaovien (hoten_gv) values ('Lesley O'' Reagan');
insert into giaovien (hoten_gv) values ('Burnard Gregson');
insert into giaovien (hoten_gv) values ('Gianna Bolliver');
select * from giaovien;

insert into monhoc (ten_mh) values ('Health Care');
insert into monhoc (ten_mh) values ('Finance');
insert into monhoc (ten_mh) values ('Technology');
insert into monhoc (ten_mh) values ('n/a');
insert into monhoc (ten_mh) values ('Finance');
insert into monhoc (ten_mh) values ('n/a');
insert into monhoc (ten_mh) values ('n/a');
insert into monhoc (ten_mh) values ('Consumer Durables');
insert into monhoc (ten_mh) values ('Consumer Services');
insert into monhoc (ten_mh) values ('n/a');
insert into monhoc (ten_mh) values ('Public Utilities');
insert into monhoc (ten_mh) values ('Consumer Services');
insert into monhoc (ten_mh) values ('Consumer Non-Durables');
insert into monhoc (ten_mh) values ('Consumer Services');
insert into monhoc (ten_mh) values ('Finance');
insert into monhoc (ten_mh) values ('Finance');
insert into monhoc (ten_mh) values ('Finance');
insert into monhoc (ten_mh) values ('Capital Goods');
insert into monhoc (ten_mh) values ('Capital Goods');
insert into monhoc (ten_mh) values ('Health Care');
select * from monhoc;

insert into lop (tenlop, magvcn, nam_hoc) values ('matrices', 10, '8/5/2024');
insert into lop (tenlop, magvcn, nam_hoc) values ('capability', 6, '4/1/2025');
insert into lop (tenlop, magvcn, nam_hoc) values ('productivity', 16, '2/18/2025');
insert into lop (tenlop, magvcn, nam_hoc) values ('access', 11, '5/11/2025');
insert into lop (tenlop, magvcn, nam_hoc) values ('next generation', 2, '11/16/2024');
insert into lop (tenlop, magvcn, nam_hoc) values ('Stand-alone', 7, '3/2/2025');
insert into lop (tenlop, magvcn, nam_hoc) values ('framework', 13, '8/30/2024');
insert into lop (tenlop, magvcn, nam_hoc) values ('Multi-tiered', 13, '2/13/2025');
insert into lop (tenlop, magvcn, nam_hoc) values ('systemic', 4, '5/5/2025');
insert into lop (tenlop, magvcn, nam_hoc) values ('implementation', 2, '4/10/2025');
insert into lop (tenlop, magvcn, nam_hoc) values ('Optional', 16, '8/26/2024');
insert into lop (tenlop, magvcn, nam_hoc) values ('well-modulated', 12, '2/25/2025');
insert into lop (tenlop, magvcn, nam_hoc) values ('help-desk', 15, '4/2/2025');
insert into lop (tenlop, magvcn, nam_hoc) values ('Configurable', 5, '3/7/2025');
insert into lop (tenlop, magvcn, nam_hoc) values ('Devolved', 19, '2/14/2025');
insert into lop (tenlop, magvcn, nam_hoc) values ('6th generation', 19, '11/6/2024');
insert into lop (tenlop, magvcn, nam_hoc) values ('Sharable', 10, '4/29/2025');
insert into lop (tenlop, magvcn, nam_hoc) values ('Monitored', 12, '2/8/2025');
insert into lop (tenlop, magvcn, nam_hoc) values ('discrete', 15, '8/3/2024');
insert into lop (tenlop, magvcn, nam_hoc) values ('Polarised', 8, '12/3/2024');

-- test foreign key invalid
-- insert into lop (tenlop, magvcn, nam_hoc) values ('Polarised', 99, '12/3/2024');
select * from lop;

insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Elias Casaro', 'Cybill Self', 'nam', '44 Kensington Alley', 13);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Colet Hunn', 'Petronilla Jeromson', 'nam', '844 Carioca Pass', 2);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Yovonnda Millery', 'Tedie Satterlee', 'nam', '14189 Northridge Road', 14);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Anson Claasen', 'Mohammed Veevers', 'nam', '8040 Gerald Drive', 18);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Abbey Mulligan', 'Leann Ottewill', 'nam', '2064 Oak Court', 3);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Madge McIlveen', 'Madelle Scohier', 'nu', '496 Tomscot Pass', 13);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Bogey MacGinley', 'Garwood Presshaugh', 'nam', '88161 Algoma Point', 17);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Friederike Shelliday', 'Zorina Langthorne', 'nu', '69 Hoard Terrace', 3);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Amity Stonall', 'Clare Gytesham', 'nam', '4710 Parkside Hill', 20);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Ike Shakspeare', 'Homer Gaish', 'nam', '4195 Ridgeview Place', 10);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Felipe Karczinski', 'Lurlene Auton', 'nu', '179 Southridge Trail', 4);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Aubree Lorden', 'Hamlen Deverick', 'nu', '932 Oxford Pass', 3);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Lindsay Yakutin', 'Aldwin Leyden', 'nu', '904 Leroy Way', 1);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Vladimir Vallack', 'Noella Guitel', 'nam', '9 Crest Line Court', 2);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Corry Balden', 'Paola Mighele', 'nam', '3270 Ohio Point', 7);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Mariellen McVie', 'Myrna Eam', 'nam', '82 Di Loreto Street', 1);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Dermot McIlwraith', 'Lotty Conew', 'nam', '55 Dawn Plaza', 9);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Malvin Girardy', 'Kelila Paddon', 'nu', '56022 Red Cloud Parkway', 2);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Lynna Bickerdicke', 'Bone Schafer', 'nam', '50893 Sundown Point', 5);
insert into hocsinh (hoten_hs, hoten_ph, gioi_tinh, dia_chi, malop) values ('Glyn Dauney', 'Teena Elliker', 'nu', '148 Saint Paul Drive', 3);
DBCC CHECKIDENT (hocsinh, RESEED, 0);


insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (6, 1, 6, 5.56, 7.06, '2025-02-13 20:48:44');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (2, 2, 16, 8.12, 8.81, '2024-10-14 14:49:41');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (5, 2, 14, 7.71, 9.33, '2024-11-30 07:35:33');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (11, 1, 6, 4.81, 1.04, '2024-09-02 16:00:55');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (11, 1, 3, 7.78, 5.07, '2025-05-03 16:06:12');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (12, 1, 6, 5.92, 2.59, '2024-10-02 00:37:52');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (3, 2, 19, 9.04, 9.87, '2024-09-20 22:17:02');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (13, 1, 2, 3.98, 4.93, '2025-02-05 21:32:39');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (3, 2, 5, 6.68, 4.38, '2025-02-10 11:28:08');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (2, 1, 2, 9.2, 7.39, '2025-02-07 03:21:13');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (20, 2, 7, 5.77, 8.99, '2024-08-24 22:30:01');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (14, 2, 17, 1.97, 6.03, '2025-03-17 22:22:23');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (8, 1, 9, 3.78, 7.27, '2024-08-11 03:51:40');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (3, 2, 1, 8.56, 3.14, '2025-01-05 10:41:47');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (3, 1, 14, 6.16, 4.27, '2025-05-10 08:37:02');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (9, 1, 19, 8.59, 2.14, '2025-02-10 19:48:22');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (16, 2, 11, 9.92, 1.82, '2025-05-07 17:05:19');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (1, 2, 8, 8.98, 9.45, '2025-03-01 12:45:25');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (5, 1, 16, 4.1, 9.28, '2025-02-19 22:10:02');
insert into ketquahoctap (mahs, hocky, mamh, diemthi_giuaky, diemthi_cuoiky, ngaygiothi_cuoiky) values (1, 2, 13, 5.35, 7.6, '2024-12-13 23:21:52');
select * from ketquahoctap;

insert into phutrachbomon (magvpt, malop, mamh, hocky) values (18, 10, 16, 1);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (5, 6, 18, 1);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (8, 6, 13, 1);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (8, 13, 10, 2);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (16, 4, 12, 2);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (16, 6, 18, 2);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (15, 19, 5, 1);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (15, 13, 16, 2);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (8, 9, 9, 2);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (3, 11, 7, 1);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (2, 13, 5, 1);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (8, 14, 15, 1);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (5, 13, 18, 2);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (16, 13, 5, 1);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (7, 18, 17, 2);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (3, 3, 5, 2);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (18, 5, 15, 2);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (13, 3, 9, 2);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (8, 10, 15, 2);
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (16, 5, 2, 1);
-- test
insert into phutrachbomon (magvpt, malop, mamh, hocky) values (166, 5, 2, 1);
select * from phutrachbomon;